const ts=require('typescript'),fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');const sqlite=new DatabaseSync(':memory:');
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:k=>imports[k]??require(k),Response,Request,URL,console});return exports}
const lib=load('lib/dashboard.ts'),membership=load('lib/memberships.ts');
sqlite.exec(fs.readFileSync('drizzle/0000_married_mattie_franklin.sql','utf8'));sqlite.exec(fs.readFileSync('drizzle/0001_wooden_joshua_kane.sql','utf8'));sqlite.exec(fs.readFileSync('drizzle/0004_mean_hiroim.sql','utf8'));
sqlite.exec(fs.readFileSync('drizzle/0005_stale_dragon_man.sql','utf8'));
const today=membership.todayBerlin(),period=today.slice(0,7),prior=new Date(today+'T12:00:00Z');prior.setUTCDate(0);const cutoff=prior.toISOString().slice(0,10);
const config={...lib.initialConfig,period,asOf:cutoff};sqlite.prepare('INSERT INTO dashboard VALUES(1,?,?,1,?)').run(JSON.stringify(config),'admin',new Date().toISOString());
const db={async batch(statements){sqlite.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());sqlite.exec('COMMIT');return results}catch(error){sqlite.exec('ROLLBACK');throw error}},prepare(sql){let v=[];return{bind(...args){v=args;return this},async first(){return sqlite.prepare(sql).get(...v)||null},async all(){return{results:sqlite.prepare(sql).all(...v)}},async run(){return{meta:{changes:Number(sqlite.prepare(sql).run(...v).changes)}}}}}};
const store={'@/db/dashboard-store':{dashboardDb:()=>db}};
const helpers=load('db/memberships-store.ts',{'./dashboard-store':{dashboardDb:()=>db},'@/lib/dashboard':lib});
const route=load('app/api/memberships/route.ts',{...store,'@/db/memberships-store':helpers,'@/lib/memberships':membership});
const dashboard=load('app/api/dashboard/route.ts',{...store,'@/db/memberships-store':helpers,'@/lib/dashboard':lib});
const id1=crypto.randomUUID(),id2=crypto.randomUUID();
const base={id:id1,clubId:'echterdingen',employee:'Test Person',reference:'TEST-001',signedOn:today};
function req(user,method='GET',body,query=''){return new Request('http://localhost/api/memberships'+query,{method,headers:{...(user?{'oai-authenticated-user-id':user}:{}),origin:'http://localhost'},...(body?{body:JSON.stringify(body)}:{})})}
async function snap(){return (await dashboard.GET(req('staff-a'))).json()}
(async()=>{
 assert.equal((await route.POST(req(null,'POST',base))).status,401);
 assert.equal((await route.POST(req('staff-a','POST',{...base,clubId:'all'}))).status,400);
 assert.equal((await route.POST(req('staff-a','POST',{...base,clubId:'unknown'}))).status,400);
 assert.equal((await route.POST(req('staff-a','POST',{...base,signedOn:cutoff}))).status,400);
 assert.equal((await route.POST(req('staff-a','POST',{...base,signedOn:'2026-02-30'}))).status,400);
 assert.equal((await route.POST(req('staff-a','POST',{...base,signedOn:'2099-12-31'}))).status,400);
 assert.equal((await route.POST(req('staff-a','POST',base))).status,201);
 assert.equal((await route.POST(req('staff-a','POST',base))).status,200);
 let s=await snap();assert.equal(s.canEdit,false);assert.equal(s.entryCounts.echterdingen,1);assert.equal(s.entryCounts.reutlingen,undefined);
 assert.equal(s.config.clubs[0].contracts,28);assert.equal(membership.countedConfig(s.config,s.entryCounts).clubs[0].contracts,29);
 assert.equal((await route.POST(req('staff-b','POST',{...base,id:crypto.randomUUID(),reference:'test-001'}))).status,409);
 assert.equal((await route.POST(req('staff-b','POST',{...base,id:id2,clubId:'reutlingen'}))).status,201);
 s=await snap();assert.equal(s.entryCounts.echterdingen,1);assert.equal(s.entryCounts.reutlingen,1);
 assert.equal((await (await route.GET(req('staff-a','GET',null,'?clubId=reutlingen'))).json()).entries.length,0);
 const journal=await (await route.GET(req('admin','GET',null,'?clubId=reutlingen'))).json();assert.equal(journal.entries.length,1);assert.equal(journal.entries[0].clubId,'reutlingen');
 assert.equal((await dashboard.PUT(req('staff-a','PUT',{config:{...config,tools:[]},revision:1}))).status,403);
 assert.equal((await route.PATCH(req('staff-a','PATCH',{id:id1}))).status,403);
 assert.equal((await route.PATCH(req('admin','PATCH',{id:id1}))).status,200);
 s=await snap();assert.equal(s.entryCounts.echterdingen,undefined);assert.equal(s.entryCounts.reutlingen,1);
 assert.equal((await route.PATCH(req('admin','PATCH',{id:id1}))).status,409);
 // Advancing the baseline absorbs entries rather than counting them twice.
 const nextConfig={...config,asOf:today,clubs:config.clubs.map(c=>c.id==='reutlingen'?{...c,contracts:11}:c)};
 assert.equal((await dashboard.PUT(req('admin','PUT',{config:nextConfig,revision:1}))).status,200);
 s=await snap();assert.equal(s.entryCounts.reutlingen,undefined);assert.equal(membership.countedConfig(s.config,s.entryCounts).clubs[1].contracts,11);
 assert.equal((await route.PATCH(req('admin','PATCH',{id:id2}))).status,409);
 assert.equal(s.config.news.enabled,false);
 const withNews={...nextConfig,news:{enabled:true,mode:'ticker',title:'PrÃ¼fmeldung',text:'Team-Info'}};
 assert.equal((await dashboard.PUT(req('staff-a','PUT',{config:withNews,revision:2}))).status,403);
 assert.equal((await dashboard.PUT(req('admin','PUT',{config:withNews,revision:2}))).status,200);
 s=await snap();assert.equal(s.config.news.mode,'ticker');assert.equal(s.config.news.text,'Team-Info');

 const reportsLib=load('lib/club-reports.ts');
 const reports=load('app/api/club-reports/route.ts',{...store,'@/db/memberships-store':helpers,'@/lib/memberships':membership,'@/lib/club-reports':reportsLib});
 sqlite.prepare('UPDATE dashboard SET config=?,revision=revision+1 WHERE id=1').run(JSON.stringify(config));
 const report={id:crypto.randomUUID(),clubId:'leinfelden',signedOn:today,counts:{...reportsLib.emptyCounts,basic1:2,allIn12:3,fifi24:1},online:4,firstName:'Test',lastName:'Person',confirmed:true};
 assert.equal((await reports.POST(req(null,'POST',report))).status,401);
 assert.equal((await reports.POST(req('staff-a','POST',{...report,confirmed:false}))).status,400);
 assert.equal((await reports.POST(req('staff-a','POST',{...report,online:7}))).status,400);
 assert.equal((await reports.POST(req('staff-a','POST',{...report,counts:{...report.counts,basic1:-1}}))).status,400);
 assert.equal((await reports.POST(req('staff-a','POST',{...report,counts:{...report.counts,basic1:1.5}}))).status,400);
 assert.equal((await reports.POST(req('staff-a','POST',{...report,lastName:''}))).status,400);
 assert.equal((await reports.POST(req('staff-a','POST',{...report,clubId:'all'}))).status,400);
 assert.equal((await reports.POST(req('staff-a','POST',report))).status,201);
 assert.equal((await reports.POST(req('staff-a','POST',report))).status,200);
 s=await snap();assert.equal(s.entryCounts.leinfelden,6);assert.equal(s.config.clubs[2].contracts,24);
 assert.equal((await reports.POST(req('staff-b','POST',{...report,id:crypto.randomUUID()}))).status,409);
 assert.equal((await route.POST(req('staff-b','POST',{...base,id:crypto.randomUUID(),clubId:'leinfelden',reference:'LEGACY-TEST'}))).status,409);
 assert.equal((await reports.POST(req('staff-a','POST',{...report,id:crypto.randomUUID(),clubId:'kornwestheim',counts:reportsLib.emptyCounts,online:0}))).status,201);
 assert.equal((await reports.POST(req('staff-a','POST',{...report,id:crypto.randomUUID(),clubId:'reutlingen'}))).status,409);
 assert.equal((await reports.PATCH(req('staff-a','PATCH',{id:report.id}))).status,403);
 assert.equal((await reports.PATCH(req('admin','PATCH',{id:report.id}))).status,200);
 assert.equal((await reports.POST(req('staff-a','POST',{...report,id:crypto.randomUUID()}))).status,201);
 const statistics=load('app/api/statistics/route.ts',{...store,'@/db/memberships-store':helpers,'@/lib/dashboard':lib});
 assert.equal((await statistics.GET(req(null,'GET',null,'?period='+period))).status,401);
 assert.equal((await statistics.GET(req('staff-a','GET',null,'?period=2026-13'))).status,400);
 assert.equal((await (await statistics.GET(req('staff-a','GET',null,'?period=2020-01'))).json()).snapshot,null);
 const before=await snap();
 const nextMonthDate=new Date(period+'-01T12:00:00Z');nextMonthDate.setUTCMonth(nextMonthDate.getUTCMonth()+1);
 const nextPeriod=nextMonthDate.toISOString().slice(0,7);
 const nextMonth={...before.config,period:nextPeriod,asOf:period+'-28',clubs:before.config.clubs.map(c=>({...c,contracts:0,departures:0}))};
 assert.equal((await dashboard.PUT(req('admin','PUT',{config:nextMonth,revision:before.revision}))).status,200);
 const historical=await (await statistics.GET(req('staff-a','GET',null,'?period='+period))).json();
 assert.equal(historical.snapshot.config.period,period);
 assert.equal(historical.snapshot.config.clubs[2].contracts,24);
 assert.equal(historical.snapshot.entryCounts.leinfelden,6);
 assert.equal(membership.countedConfig(historical.snapshot.config,historical.snapshot.entryCounts).clubs[2].contracts,30);
 assert.equal((await dashboard.PUT(req('admin','PUT',{config:{...before.config,asOf:today},revision:before.revision}))).status,409);
 const preserved=await (await statistics.GET(req('staff-a','GET',null,'?period='+period))).json();
 assert.equal(preserved.snapshot.config.asOf,before.config.asOf);
 const active=await (await statistics.GET(req('staff-a','GET',null,'?period='+nextPeriod))).json();
 assert.equal(active.snapshot.config.clubs[2].contracts,0);
 assert.equal(active.snapshot.entryCounts.leinfelden,undefined);
 console.log('PASS: monthly archive preserves baseline and club-specific CÜ totals; current month separated; empty months; validation; authentication; stale updates leave archive unchanged.');
 console.log('PASS: daily tariff total excludes online subset; validation; idempotency; one active report per club/day; legacy overlap prevention; zero day; admin cancellation and re-entry.');
 console.log('PASS: actual SQLite queries; staff entry permission; isolated clubs; reference duplicates; retry idempotency; date checks; own history; admin-only config and cancellation; baseline aggregation without double count.');
})().catch(e=>{console.error(e);process.exitCode=1});
