import {dashboardDb} from '@/db/dashboard-store';
import {readDashboard,dashboardSnapshot} from '@/db/memberships-store';
import {reportSchema,reportTotal} from '@/lib/club-reports';
import {entryDateError} from '@/lib/memberships';
import type {Config} from '@/lib/dashboard';
import {z} from 'zod';
export const dynamic='force-dynamic';
function reply(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
export async function GET(r:Request){const user=r.headers.get('oai-authenticated-user-id');if(!user)return reply({error:'Anmeldung erforderlich.'},401);try{const current=await readDashboard();if(!current)return reply({error:'Dashboard nicht bereit.'},503);const club=new URL(r.url).searchParams.get('clubId');const config=JSON.parse(current.config) as Config;if(!config.clubs.some(c=>c.id===club))return reply({error:'Unbekannter Standort.'},400);const result=await dashboardDb().prepare('SELECT id,signed_on AS signedOn,total,online,cancelled_at AS cancelledAt FROM club_reports WHERE club_id=? AND substr(signed_on,1,7)=? ORDER BY signed_on DESC,created_at DESC LIMIT 100').bind(club,config.period).all();return reply({entries:result.results})}catch{return reply({error:'Tagesübersichten konnten nicht geladen werden.'},503)}}
export async function POST(r:Request){const user=r.headers.get('oai-authenticated-user-id');if(!user)return reply({error:'Anmeldung erforderlich.'},401);if(r.headers.get('origin')!==new URL(r.url).origin)return reply({error:'Ungültiger Ursprung.'},403);try{
 const raw=await r.text();if(raw.length>4096)return reply({error:'Eingabe zu groß.'},413);let json;try{json=JSON.parse(raw)}catch{return reply({error:'Ungültige Eingabe.'},400)}
 const parsed=reportSchema.safeParse(json);if(!parsed.success)return reply({error:parsed.error.issues[0].message},400);
 const e=parsed.data,current=await readDashboard();if(!current)return reply({error:'Dashboard nicht bereit.'},503);const config=JSON.parse(current.config) as Config;if(!config.clubs.some(c=>c.id===e.clubId))return reply({error:'Unbekannter Standort.'},400);
 const counts=JSON.stringify(e.counts),total=reportTotal(e.counts);
 const existing=await dashboardDb().prepare('SELECT * FROM club_reports WHERE id=?').bind(e.id).first<Record<string,unknown>>();
 if(existing){if(existing.created_by===user&&existing.club_id===e.clubId&&existing.signed_on===e.signedOn&&existing.counts===counts&&existing.online===e.online&&existing.first_name===e.firstName&&existing.last_name===e.lastName&&!existing.cancelled_at)return reply({snapshot:await dashboardSnapshot(current,user)});return reply({error:'Diese Erfassung wurde bereits gespeichert. Bitte neu beginnen.'},409)}
 const error=entryDateError(config,e.signedOn);if(error)return reply({error},400);
 const result=await dashboardDb().prepare(`INSERT OR IGNORE INTO club_reports (id,club_id,signed_on,counts,online,total,first_name,last_name,created_by,created_at) SELECT ?,?,?,?,?,?,?,?,?,? FROM dashboard WHERE id=1 AND revision=? AND NOT EXISTS (SELECT 1 FROM memberships WHERE club_id=? AND signed_on=? AND cancelled_at IS NULL)`).bind(e.id,e.clubId,e.signedOn,counts,e.online,total,e.firstName,e.lastName,user,new Date().toISOString(),current.revision,e.clubId,e.signedOn).run();
 if(!result.meta.changes)return reply({error:'Für diesen Standort und Tag gibt es bereits eine CÜ oder einzelne Abschlüsse, oder der Berichtsstand wurde geändert. Bitte vom Admin prüfen lassen; es wird nichts doppelt gezählt.'},409);
 return reply({snapshot:await dashboardSnapshot(current,user),total},201);
 }catch(e){console.error('Club report save failed',e);return reply({error:'Speichern nicht bestätigt. Erneut versuchen zählt dieselbe CÜ nicht doppelt.'},503)}}
export async function PATCH(r:Request){const user=r.headers.get('oai-authenticated-user-id');if(!user)return reply({error:'Anmeldung erforderlich.'},401);if(r.headers.get('origin')!==new URL(r.url).origin)return reply({error:'Ungültiger Ursprung.'},403);try{const current=await readDashboard();if(!current||current.owner!==user)return reply({error:'Nur der Admin kann eine CÜ stornieren.'},403);const raw=await r.text();if(raw.length>1024)return reply({error:'Eingabe zu groß.'},413);let json;try{json=JSON.parse(raw)}catch{return reply({error:'Ungültige Eingabe.'},400)}const parsed=z.object({id:z.string().uuid()}).strict().safeParse(json);if(!parsed.success)return reply({error:'Ungültige Eingabe.'},400);const config=JSON.parse(current.config) as Config;const result=await dashboardDb().prepare('UPDATE club_reports SET cancelled_at=?,cancelled_by=? WHERE id=? AND cancelled_at IS NULL AND signed_on>? AND substr(signed_on,1,7)=? AND EXISTS(SELECT 1 FROM dashboard WHERE id=1 AND owner=? AND revision=?)').bind(new Date().toISOString(),user,parsed.data.id,config.asOf,config.period,user,current.revision).run();if(!result.meta.changes)return reply({error:'Nicht stornierbar: bereits storniert oder im Ausgangsstand enthalten.'},409);return reply({snapshot:await dashboardSnapshot(current,user)})}catch{return reply({error:'Stornieren fehlgeschlagen.'},503)}}
