'use client';
import NewsBanner from './news-banner';
import ContractStats from './contract-stats';
import MembershipPanel from './membership-panel';
import {countedConfig} from '@/lib/memberships';
import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, ArrowUpRight, BarChart3, Building2, Check, ChevronRight, Dumbbell, ExternalLink, GripVertical, LayoutGrid, Link2, Mail, Pencil, Plus, RefreshCw, Save, Settings2, Target, Trash2, Users, X, CircleAlert, CalendarDays, PanelTop, ClipboardList, FileText, FolderOpen, CreditCard, Megaphone, HeartPulse, Activity, Bike, Trophy, Timer, Clock, CalendarCheck, LogIn, BookOpen, GraduationCap, Lightbulb, CircleHelp, ShieldCheck } from 'lucide-react';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue,SelectGroup,SelectLabel } from '@/components/ui/select';
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle } from '@/components/ui/sheet';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { Progress } from '@/components/ui/progress';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { Config,Snapshot,Tool,configSchema,toolSchema } from '@/lib/dashboard';

const icons={members:Users,fitness:Dumbbell,mail:Mail,chart:BarChart3,leads:Target,office:PanelTop,link:Link2, tasks:ClipboardList,contracts:FileText,files:FolderOpen,payments:CreditCard,marketing:Megaphone,health:HeartPulse,activity:Activity,cycling:Bike,awards:Trophy,timer:Timer,clock:Clock,appointments:CalendarCheck,checkin:LogIn,knowledge:BookOpen,training:GraduationCap,ideas:Lightbulb,help:CircleHelp,security:ShieldCheck};
const iconNames:Record<Tool['icon'],string>={members:'Mitglieder',fitness:'Krafttraining',mail:'E-Mail',chart:'Statistik',leads:'Ziele & Leads',office:'Office',link:'Weblink',tasks:'Aufgaben',contracts:'Verträge',files:'Dateien',payments:'Zahlungen',marketing:'Marketing',health:'Gesundheit',activity:'Ausdauer',cycling:'Cycling',awards:'Erfolge',timer:'Stoppuhr',clock:'Arbeitszeit',appointments:'Termine',checkin:'Check-in',knowledge:'Wissen',training:'Schulungen',ideas:'Ideen',help:'Hilfe',security:'Sicherheit'};
const iconGroups:{label:string;items:Tool['icon'][]}[]=[
 {label:'Verwaltung',items:['members','mail','chart','office','link','tasks','contracts','files','payments','marketing','security']},
 {label:'Fitness',items:['fitness','leads','health','activity','cycling','awards']},
 {label:'Zeit & Termine',items:['timer','clock','appointments','checkin']},
 {label:'Wissen',items:['knowledge','training','ideas','help']},
];
function IconPicker({value,onChange}:{value:Tool['icon'];onChange:(s:Tool['icon'])=>void}){return <Select value={value} onValueChange={s=>onChange(s as Tool['icon'])}><SelectTrigger aria-label="Kachelsymbol" className="picker"><SelectValue/></SelectTrigger><SelectContent>{iconGroups.map(group=><SelectGroup key={group.label}><SelectLabel>{group.label}</SelectLabel>{group.items.map(key=>{const Icon=icons[key];return <SelectItem key={key} value={key}><span className="inline-flex items-center gap-2"><Icon size={18} aria-hidden="true"/>{iconNames[key]}</span></SelectItem>})}</SelectGroup>)}</SelectContent></Select>}
const colorNames={orange:'Orange',blue:'Blau',green:'Grün',purple:'Violett',slate:'Graphit'};
const fmt=(n:number)=>new Intl.NumberFormat('de-DE').format(n);
const date=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'});
const month=(s:string)=>new Date(s+'-01T12:00:00').toLocaleDateString('de-DE',{month:'long',year:'numeric'});
function Picker({value,onChange,items,label}:{value:string,onChange:(s:string)=>void,items:{value:string,label:string}[],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>}
function ToolIcon({tool}:{tool:Tool}){const Icon=icons[tool.icon];return <span className={'tool-icon '+tool.color}><Icon size={27} strokeWidth={1.7}/></span>}

export default function ClubDashboard(){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[error,setError]=useState(''),[connection,setConnection]=useState('loading');
 const [club,setClub]=useState('all'),[admin,setAdmin]=useState(false),[draft,setDraft]=useState<Config|null>(null),[saving,setSaving]=useState(false),[details,setDetails]=useState(false);
 const [membershipOpen,setMembershipOpen]=useState(false);
 const [partnersOpened,setPartnersOpened]=useState(false),[partnersVisible,setPartnersVisible]=useState(false);
 const [studioOpened,setStudioOpened]=useState(false),[studioVisible,setStudioVisible]=useState(false);
 const displayConfig=snapshot?countedConfig(snapshot.config,snapshot.entryCounts):null;
 const [editing,setEditing]=useState<Tool|null>(null),[editorError,setEditorError]=useState(''),[confirmDelete,setConfirmDelete]=useState(false),[saveError,setSaveError]=useState('');
 const current=useRef<Snapshot|null>(null),inAdmin=useRef(false),statsTrigger=useRef<HTMLElement|null>(null);
 useEffect(()=>{inAdmin.current=admin},[admin]);
 async function refresh(){
  try{const res=await fetch('/api/dashboard',{cache:'no-store'});const data=await res.json() as Snapshot & {error?:string};if(!res.ok)throw new Error(data.error);current.current=data;
   if(!data.canEdit){setAdmin(false);inAdmin.current=false;setEditing(null)}
   if(!inAdmin.current){setSnapshot(data);setDraft(structuredClone(data.config))}setConnection('ready');setError('');
  }catch(e){setConnection('error');setError(e instanceof Error?e.message:'Verbindung fehlgeschlagen.')}
 }
 useEffect(()=>{const saved=localStorage.getItem('top-sports-club');if(saved)setClub(saved);void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh()},20000);const focus=()=>void refresh();window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus)}},[]);
 const dirty=!!draft&&!!snapshot&&JSON.stringify(draft)!==JSON.stringify(snapshot.config);
 useEffect(()=>{const unload=(e:BeforeUnloadEvent)=>{if(dirty&&admin){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload)},[dirty,admin]);
 function chooseClub(id:string){setClub(id);localStorage.setItem('top-sports-club',id)}
 function openAdmin(){if(!snapshot?.canEdit)return;setDraft(structuredClone(snapshot.config));setAdmin(true);setSaveError('')}
 function discard(){if(current.current){setSnapshot(current.current);setDraft(structuredClone(current.current.config))}setAdmin(false);setSaveError('')}
 async function save(){if(!draft||!snapshot?.canEdit)return;const parsed=configSchema.safeParse(draft);if(!parsed.success){setSaveError('Bitte alle Zahlen, Datumsfelder und Kachel-Links prüfen.');return}setSaving(true);setSaveError('');
  try{const res=await fetch('/api/dashboard',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({config:parsed.data,revision:snapshot.revision})});const data=await res.json() as Snapshot & {error?:string};if(!res.ok)throw new Error(data.error);setSnapshot(data);current.current=data;setDraft(structuredClone(data.config));setConnection('ready');toast.success('Gespeichert. Die Club-Seiten übernehmen die Änderungen automatisch.');}
  catch(e){setSaveError(e instanceof Error?e.message:'Speichern fehlgeschlagen.')}finally{setSaving(false)}
 }
 function move(id:string,direction:number){if(!draft||!snapshot?.canEdit)return;const a=[...draft.tools],from=a.findIndex(x=>x.id===id),to=from+direction;if(to<0||to>=a.length)return;[a[from],a[to]]=[a[to],a[from]];setDraft({...draft,tools:a})}
 function edit(tool:Tool){if(!snapshot?.canEdit)return;setEditing({...tool});setEditorError('');setConfirmDelete(false)}
 function applyTool(e:React.FormEvent){e.preventDefault();if(!editing||!draft||!snapshot?.canEdit)return;const parsed=toolSchema.safeParse(editing);if(!parsed.success){setEditorError(parsed.error.issues[0].message);return}const exists=draft.tools.some(t=>t.id===editing.id);setDraft({...draft,tools:exists?draft.tools.map(t=>t.id===editing.id?parsed.data:t):[...draft.tools,parsed.data]});setEditing(null)}
 function viewStats(){statsTrigger.current=document.activeElement as HTMLElement;setDetails(true)}
 function toolContent(t:Tool){return <><div className="tile-top"><ToolIcon tool={t}/>{t.kind==='statistics'?<ChevronRight className="launch-icon" size={19}/>:<ArrowUpRight className="launch-icon" size={19}/>}</div><h3>{t.name}</h3><p>{t.description}</p><span className={'tile-bottom '+(!t.url&&t.kind==='link'?'unconfigured':'')}>{t.kind==='partners'?'Partnerverwaltung öffnen':t.kind==='design-studio'?'Editor öffnen':t.kind==='memberships'?'Mitgliedschaft eintragen':t.kind==='statistics'?'Zahlen ansehen':t.url?'Tool öffnen':'Club-Link fehlt'}{!t.url&&t.kind==='link'?<Link2 size={14}/>:<span/>}</span></>}
 return <div className="app-shell"><Toaster position="bottom-right" theme="dark"/>
  <header className="masthead" inert={studioVisible||partnersVisible}><a href="/" className="brand" aria-label="TOP SPORTS Startseite"><img className="brand-logo" src="/topsports-logo.svg" alt="TOP SPORTS Fitnessclubs" width="116" height="62"/><span className="brand-divider"/><span className="product-name">Club-Cockpit</span></a><span className="draft-badge">Erster Entwurf</span><div className="header-actions">{snapshot?.signedIn===false&&<a className="button secondary" href="/signin-with-chatgpt?return_to=%2F" target="_top">Anmelden</a>}{snapshot?.canEdit&&<button className={'button secondary '+(admin?'selected':'')} onClick={()=>admin?discard():openAdmin()}>{admin?<X size={17}/>:<Settings2 size={17}/>}<span>{admin?(dirty?'Entwurf verwerfen':'Verwaltung schließen'):'Verwalten'}</span></button>}</div></header>
  {!snapshot?<main className="loading-view"><LayoutGrid size={38}/><h1>{error?'Club-Cockpit nicht erreichbar':'Dein Club-Cockpit wird geladen'}</h1><p>{error||'Tools und Vertragszahlen werden abgerufen.'}</p>{error&&<button className="button primary" onClick={()=>void refresh()}><RefreshCw size={17}/>Erneut versuchen</button>}</main>:
  <main className="workspace" inert={studioVisible||partnersVisible}>
   <section className="page-heading"><div><h1>{admin?'Zentrale Verwaltung':<>Dein Club. <span>Alles an einem Ort.</span></>}</h1><p>{admin?'Kacheln und Vertragszahlen für alle Clubs pflegen.':'Die wichtigsten Tools für deinen Arbeitsalltag.'}</p></div>{!admin&&<div className="club-picker"><Building2 size={18}/><Picker value={snapshot.config.clubs.some(c=>c.id===club)?club:'all'} onChange={chooseClub} label="Standort auswählen" items={[{value:'all',label:'Alle Standorte'},...snapshot.config.clubs.map(c=>({value:c.id,label:c.name}))]}/></div>}</section>
   {connection==='error'&&<div className="notice error" role="alert"><CircleAlert size={18}/><span>{error} Zuletzt geladene Daten werden angezeigt.</span><button onClick={()=>void refresh()}>Erneut versuchen</button></div>}
   {admin&&snapshot.canEdit&&draft?<>
    <div className="admin-intro"><span><Building2 size={17}/>Gilt für alle {draft.clubs.length} Clubs</span><span>Änderungen werden erst mit „Für alle Clubs speichern“ übernommen.</span></div>
    <Tabs defaultValue="tools" className="admin-tabs"><TabsList><TabsTrigger value="tools"><LayoutGrid size={16}/>Kacheln</TabsTrigger><TabsTrigger value="numbers"><BarChart3 size={16}/>Vertragszahlen</TabsTrigger><TabsTrigger value="news"><Megaphone size={16}/>News</TabsTrigger></TabsList>
     <TabsContent value="tools"><div className="section-heading"><h2>Tools & Reihenfolge <span>{draft.tools.length}</span></h2><button className="button primary" disabled={draft.tools.length>=30} onClick={()=>edit({id:crypto.randomUUID(),name:'',description:'',url:'',icon:'link',color:'slate',kind:'link'})}><Plus size={17}/>Kachel hinzufügen</button></div><p className="section-note">Mit den Pfeilen verschieben. Name, Link und Gestaltung unter „Bearbeiten“ anpassen.</p><div className="admin-grid">{draft.tools.map((t,i)=><article className="edit-tile" key={t.id}><div className="edit-tile-title"><ToolIcon tool={t}/><div><h3>{t.name}</h3><p>{t.kind==='partners'?'Integrierte Partnerverwaltung':t.kind==='design-studio'?'Integrierter Design-Editor':t.kind==='memberships'?'Interne Clubübersicht':t.kind==='statistics'?'Interne Statistik':t.url||'Club-Link fehlt'}</p></div></div><div className="edit-tile-actions"><div className="order-buttons"><button className="icon-button" aria-label={`${t.name} nach vorne verschieben`} disabled={i===0} onClick={()=>move(t.id,-1)}><ArrowUp size={16}/></button><button className="icon-button" aria-label={`${t.name} nach hinten verschieben`} disabled={i===draft.tools.length-1} onClick={()=>move(t.id,1)}><ArrowDown size={16}/></button><span>Position {i+1}</span></div><button className="text-button" onClick={()=>edit(t)}><Pencil size={15}/>Bearbeiten</button></div></article>)}</div>{!draft.tools.length&&<div className="empty-state"><LayoutGrid/><h3>Noch keine Kacheln</h3><p>Füge das erste Tool für eure Clubs hinzu.</p></div>}</TabsContent>
     <TabsContent value="numbers"><div className="section-heading"><h2>Vertragszahlen pflegen</h2></div><div className="date-fields"><label>Berichtsmonat<input type="month" value={draft.period} onChange={e=>setDraft({...draft,period:e.target.value})}/></label><label>Ausgangsstand bis einschließlich<input type="date" value={draft.asOf} onChange={e=>setDraft({...draft,asOf:e.target.value})}/></label></div><p className="section-note">Ausgangsstand: bereits erfasste Neuverträge bis einschließlich des Datums. Spätere CÜ-Einträge werden automatisch addiert. Beim Verschieben des Datums müssen alle Abschlüsse bis zu diesem Tag in den Ausgangsstand übernommen werden. Monatsziel als Gesamtzahl eingeben.</p><div className="data-table"><Table><TableHeader><TableRow><TableHead>Standort</TableHead><TableHead>Ausgangsstand</TableHead><TableHead>Monatsziel</TableHead><TableHead>Abgänge</TableHead></TableRow></TableHeader><TableBody>{draft.clubs.map(c=><TableRow key={c.id}><TableCell className="club-name">{c.name}</TableCell>{(['contracts','target','departures'] as const).map(key=><TableCell key={key}><input className="number-input" aria-label={`${c.name} ${key==='contracts'?'Neuverträge':key==='target'?'Monatsziel':'Abgänge'}`} type="number" min="0" max="999999" step="1" value={Number.isNaN(c[key])?'':c[key]} onChange={e=>setDraft({...draft,clubs:draft.clubs.map(x=>x.id===c.id?{...x,[key]:e.target.value===''?NaN:Number(e.target.value)}:x)})}/></TableCell>)}</TableRow>)}</TableBody></Table></div></TabsContent>
     <TabsContent value="news"><div className="section-heading"><h2>News für alle Clubs</h2></div><div className="news-editor"><label className="news-enable"><input type="checkbox" checked={draft.news.enabled} onChange={e=>setDraft({...draft,news:{...draft.news,enabled:e.target.checked}})}/>News auf der Startseite anzeigen</label><label>Darstellung<Picker label="News-Darstellung" value={draft.news.mode} onChange={mode=>setDraft({...draft,news:{...draft.news,mode:mode as 'static'|'ticker'}})} items={[{value:'static',label:'Statisch über den Tools'},{value:'ticker',label:'Laufschrift im orangenen Banner'}]}/></label><label>Überschrift (optional)<input value={draft.news.title} maxLength={100} onChange={e=>setDraft({...draft,news:{...draft.news,title:e.target.value}})} placeholder="Aktuelles"/></label><label>Meldung<textarea rows={5} maxLength={1500} value={draft.news.text} onChange={e=>setDraft({...draft,news:{...draft.news,text:e.target.value}})} placeholder="Was sollen eure Clubs wissen?"/><small>{draft.news.text.length} / 1.500 Zeichen</small></label><p className="section-note">Diese Meldung gilt für alle Clubs. Mit „Für alle Clubs speichern“ wird sie übernommen. Ohne Meldung bleibt der Bereich ausgeblendet.</p></div>{draft.news.text.trim()&&<div className="news-preview"><h3>Vorschau</h3><NewsBanner news={{...draft.news,enabled:true}}/></div>}</TabsContent>
    </Tabs>
    <div className="save-bar"><div><strong>{dirty?'Nicht gespeicherte Änderungen':'Alles gespeichert'}</strong><p>{saveError||'Geöffnete Club-Seiten aktualisieren sich innerhalb von 20 Sekunden.'}</p></div><div className="save-actions"><button className="button secondary" onClick={discard} disabled={saving}>{dirty?'Änderungen verwerfen':'Zur Startseite'}</button><button className="button primary" onClick={()=>void save()} disabled={saving||!dirty}>{saving?<RefreshCw size={17} className="spin"/>:<Save size={17}/>} {saving?'Wird gespeichert …':'Für alle Clubs speichern'}</button></div></div>{saveError&&<p className="form-error" role="alert">{saveError}</p>}
   </>:<>
    <NewsBanner news={snapshot.config.news}/><div className="main-columns"><section className="tools-section"><div className="section-heading"><h2>Deine Tools</h2><span className="quiet-count">{snapshot.config.tools.length} Anwendungen</span></div><div className="tools-grid">{snapshot.config.tools.map(t=>t.kind==='link'&&t.url?<a className="tool-tile" key={t.id} href={t.url} target="_blank" rel="noopener noreferrer" aria-label={`${t.name} in neuem Tab öffnen`}>{toolContent(t)}</a>:<button className="tool-tile" key={t.id} onClick={()=>t.kind==='partners'?(setPartnersOpened(true),setPartnersVisible(true)):t.kind==='design-studio'?(setStudioOpened(true),setStudioVisible(true)):t.kind==='memberships'?setMembershipOpen(true):t.kind==='statistics'?viewStats():snapshot.canEdit?(openAdmin(),edit(t)):toast.info('Der Club-Link wird von der zentralen Verwaltung hinterlegt.')}>{toolContent(t)}</button>)}</div>{snapshot.config.tools.length===0&&<div className="empty-state"><LayoutGrid/><h3>Hier starten eure Tools</h3><p>In der Verwaltung die erste Kachel hinzufügen.</p></div>}<p className="tools-footnote"><ExternalLink size={14}/>Externe Tools öffnen sich in einem neuen Tab.</p></section>
    <Monthly config={displayConfig!} club={club} onDetails={viewStats}/></div>

    <div className="setup-note"><span className="setup-icon"><Link2 size={19}/></span><div><strong>{snapshot.config.tools.filter(t=>t.kind==='link'&&!t.url).length?`${snapshot.config.tools.filter(t=>t.kind==='link'&&!t.url).length} Club-Links noch hinterlegen`:'Eure Tools sind startklar'}</strong><p>{snapshot.config.tools.filter(t=>t.kind==='link'&&!t.url).length?'Für Magicline, Mywellness und weitere interne Tools eure eigenen Zugangsadressen verwenden.':'Kacheln und Links werden zentral für alle Clubs gepflegt.'}</p></div>{snapshot.canEdit&&<button className="text-button" onClick={openAdmin}>Zur Verwaltung<ChevronRight size={16}/></button>}</div>
   </>}
   <footer><span>TOP SPORTS <span className="footer-separator">/</span> Club-Cockpit</span><span className="sync-state"><RefreshCw size={13}/>{connection==='ready'?'Zentral gespeichert · automatische Aktualisierung':'Verbindung wird geprüft'}</span><span>Version {snapshot.revision}</span></footer>
  </main>}
  {snapshot&&details&&<ContractStats snapshot={snapshot} onClose={()=>setDetails(false)} trigger={statsTrigger}/>}
  {partnersOpened&&<section className="studio-module" hidden={!partnersVisible} aria-label="Firmen- und Vereinsfitness"><div className="studio-module-bar"><h2>Firmen- & Vereinsfitness</h2><button className="button secondary" onClick={()=>setPartnersVisible(false)}><X size={17}/>Zur Clubübersicht</button></div><iframe title="TOP SPORTS Partnerverwaltung" src="/modules/partnerverwaltung/index.html"/></section>}
  {studioOpened&&<section className="studio-module" hidden={!studioVisible} aria-label="TOP SPORTS Editor"><div className="studio-module-bar"><h2>TOP SPORTS Editor</h2><button className="button secondary" onClick={()=>setStudioVisible(false)}><X size={17}/>Zur Clubübersicht</button></div><iframe title="TOP SPORTS Design Studio" src="/modules/design-studio/index.html"/></section>}
  {membershipOpen&&snapshot&&<MembershipPanel snapshot={snapshot} onClose={()=>setMembershipOpen(false)} onSnapshot={data=>{setSnapshot(data);current.current=data;setDraft(structuredClone(data.config));setConnection('ready')}}/>}
  <Sheet open={!!editing&&!!snapshot?.canEdit} onOpenChange={open=>{if(!open)setEditing(null)}}><SheetContent className="tool-sheet"><SheetHeader><SheetTitle>{draft?.tools.some(t=>t.id===editing?.id)?'Kachel bearbeiten':'Neue Kachel'}</SheetTitle><SheetDescription>So erscheint das Tool auf den Startseiten eurer Clubs.</SheetDescription></SheetHeader>{editing&&snapshot?.canEdit&&<form onSubmit={applyTool} className="tool-form"><div className="tile-preview"><ToolIcon tool={editing}/><div><strong>{editing.name||'Dein neues Tool'}</strong><p>{editing.description||'Kurze Beschreibung'}</p></div></div><label>Name<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="z. B. Lead Management" required maxLength={45}/></label><label>Beschreibung<input value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})} maxLength={100} placeholder="Wofür nutzt ihr dieses Tool?"/></label><label>Ziel<Picker label="Kachelziel" value={editing.kind} onChange={s=>setEditing({...editing,kind:s as Tool['kind']})} items={[{value:'link',label:'Externe Webseite'},{value:'statistics',label:'Interne Vertragszahlen'},{value:'memberships',label:'CÜ – Mitgliedschaften erfassen'},{value:'design-studio',label:'TOP SPORTS Editor'},{value:'partners',label:'Firmen- & Vereinsfitness'}]}/></label>{editing.kind==='link'&&<label>Webadresse<input type="url" value={editing.url} onChange={e=>setEditing({...editing,url:e.target.value})} placeholder="https://euer-club.example"/><small>Leer lassen, solange die Adresse noch nicht bekannt ist.</small></label>}<div className="form-two"><label>Symbol<IconPicker value={editing.icon} onChange={icon=>setEditing({...editing,icon})}/></label><label>Farbe<Picker value={editing.color} label="Kachelfarbe" onChange={s=>setEditing({...editing,color:s as Tool['color']})} items={Object.entries(colorNames).map(([value,label])=>({value,label}))}/></label></div>{editorError&&<p role="alert" className="form-error">{editorError}</p>}<button className="button primary full" type="submit"><Check size={17}/>In Entwurf übernehmen</button><p className="section-note">Anschließend mit „Für alle Clubs speichern“ veröffentlichen.</p>{draft?.tools.some(t=>t.id===editing.id)&&<div className="delete-zone">{confirmDelete?<><p>„{editing.name}“ aus dem Entwurf entfernen?</p><div className="save-actions"><button type="button" className="button danger" onClick={()=>{setDraft({...draft,tools:draft.tools.filter(t=>t.id!==editing.id)});setEditing(null)}}>Kachel entfernen</button><button type="button" className="button secondary" onClick={()=>setConfirmDelete(false)}>Behalten</button></div></>:<button type="button" className="text-button danger-text" onClick={()=>setConfirmDelete(true)}><Trash2 size={16}/>Kachel entfernen</button>}</div>}</form>}</SheetContent></Sheet>
 </div>
}

function Monthly({config,club,onDetails}:{config:Config,club:string,onDetails:()=>void}){
 const clubs=config.clubs.some(c=>c.id===club)?config.clubs.filter(c=>c.id===club):config.clubs;
 const contracts=clubs.reduce((a,c)=>a+c.contracts,0),target=clubs.reduce((a,c)=>a+c.target,0),departures=clubs.reduce((a,c)=>a+c.departures,0),percent=target?Math.round(contracts/target*100):0;
 return <aside className="monthly-panel"><div className="monthly-heading"><h2>Der Monat im Blick</h2><CalendarDays size={19}/></div><p className="month-name">{month(config.period)}</p><div className="scope-label"><Building2 size={14}/>{clubs.length===1?clubs[0].name:'Alle '+clubs.length+' Standorte'}</div><div className="main-number">{fmt(contracts)}<span>Neuverträge</span></div><div className="progress-label"><span>Monatsziel {fmt(target)}</span><strong>{target?percent+' %':'Nicht gesetzt'}</strong></div><Progress className="goal-progress" value={Math.min(percent,100)} aria-label="Monatsziel erreicht"/><div className="monthly-secondary"><div><strong>{fmt(Math.max(0,target-contracts))}</strong><span>Noch zum Ziel</span></div><div><strong>{fmt(departures)}</strong><span>Abgänge</span></div></div><button className="monthly-link" onClick={onDetails}>Vertragszahlen ansehen<ArrowUpRight size={18}/></button><p className="data-stamp">Ausgangsstand bis {date(config.asOf)}<br/>Inklusive neuer CÜ-Einträge im Berichtsmonat</p></aside>
}

