 'use client';
import {useEffect,useRef,useState} from 'react';
import {Building2,Check,ChevronLeft,RefreshCw,Save} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import type {Snapshot} from '@/lib/dashboard';
import {entryDateError,todayBerlin} from '@/lib/memberships';
import {tariffKeys,tariffLabels,emptyCounts,countsSchema,reportSchema,reportTotal,type TariffCounts} from '@/lib/club-reports';
const date=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('de-DE');
const steps=['Standort','Tag','Tarife','Online','Gesamtzahl','Mitarbeiter'];
type HistoryEntry={id:string;signedOn:string;total:number;online:number;cancelledAt:string|null};
export default function MembershipPanel({snapshot,onSnapshot,onClose}:{snapshot:Snapshot;onSnapshot:(s:Snapshot)=>void;onClose:()=>void}){
 const [step,setStep]=useState(0),[clubId,setClubId]=useState(''),[signedOn,setSignedOn]=useState(todayBerlin());
 const [counts,setCounts]=useState<Record<keyof TariffCounts,string>>(()=>Object.fromEntries(tariffKeys.map(k=>[k,''])) as Record<keyof TariffCounts,string>),[online,setOnline]=useState(''),[firstName,setFirstName]=useState(''),[lastName,setLastName]=useState('');
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[entries,setEntries]=useState<HistoryEntry[]>([]),[historyError,setHistoryError]=useState(''),[historyVersion,setHistoryVersion]=useState(0),[cancelId,setCancelId]=useState('');
 const requestId=useRef(crypto.randomUUID()),pending=useRef(false),heading=useRef<HTMLHeadingElement>(null);
 const club=snapshot.config.clubs.find(c=>c.id===clubId);
 const numeric=Object.fromEntries(tariffKeys.map(k=>[k,Number(counts[k]||0)])) as TariffCounts;
 const total=reportTotal(numeric),onlineCount=Number(online||0);
 useEffect(()=>{heading.current?.focus()},[step,saved]);
 useEffect(()=>{setEntries([]);setHistoryError('');if(!clubId)return;const abort=new AbortController();fetch('/api/club-reports?clubId='+encodeURIComponent(clubId),{signal:abort.signal,cache:'no-store'}).then(async r=>{const d=await r.json() as {entries:HistoryEntry[];error?:string};if(!r.ok)throw Error(d.error);if(!abort.signal.aborted)setEntries(d.entries)}).catch(e=>{if(!abort.signal.aborted)setHistoryError(e.message)});return()=>abort.abort()},[clubId,historyVersion,snapshot.config.period]);
 function go(next:number){setError('');setStep(next)}
 function next(e:React.FormEvent){e.preventDefault();setError('');if(step===0&&!club){setError('Bitte einen Standort auswählen.');return}if(step===1){const problem=entryDateError(snapshot.config,signedOn);if(problem){setError(problem);return}if(entries.some(e=>e.signedOn===signedOn&&!e.cancelledAt)){setError('Für diesen Tag wurde bereits eine CÜ erfasst. Bitte den Admin kontaktieren.');return}}
 if(step===2&&!countsSchema.safeParse(numeric).success){setError('Bitte nur ganze Zahlen von 0 bis 9.999 eingeben.');return}
 if(step===3&&(!Number.isInteger(onlineCount)||onlineCount<0||onlineCount>total)){setError('Online ist ein Anteil der Gesamtzahl und darf zwischen 0 und '+total+' liegen.');return}go(step+1)}
 async function save(e:React.FormEvent){e.preventDefault();if(pending.current)return;setError('');const parsed=reportSchema.safeParse({id:requestId.current,clubId,signedOn,counts:numeric,online:onlineCount,firstName,lastName,confirmed:true});if(!parsed.success){setError(parsed.error.issues[0].message);return}pending.current=true;setBusy(true);try{const r=await fetch('/api/club-reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(parsed.data)});const data=await r.json() as {snapshot:Snapshot;error?:string};if(!r.ok)throw Error(data.error);onSnapshot(data.snapshot);setSaved(true)}catch(e){setError(e instanceof Error?e.message:'Speichern fehlgeschlagen.')}finally{pending.current=false;setBusy(false)}}
 async function cancel(){if(!cancelId||pending.current)return;pending.current=true;setBusy(true);try{const r=await fetch('/api/club-reports',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:cancelId})});const data=await r.json() as {snapshot:Snapshot;error?:string};if(!r.ok)throw Error(data.error);onSnapshot(data.snapshot);setCancelId('');setHistoryVersion(v=>v+1)}catch(e){setError(e instanceof Error?e.message:'Stornierung fehlgeschlagen.')}finally{pending.current=false;setBusy(false)}}
 return <Dialog open onOpenChange={open=>{if(!open&&!pending.current)onClose()}}><DialogContent className="cu-wizard" onInteractOutside={e=>e.preventDefault()}><DialogHeader><DialogTitle>CÜ (Clubübersicht)</DialogTitle><DialogDescription>{saved?'Tagesübersicht gespeichert':`Schritt ${step+1} von 6 · ${steps[step]}`}</DialogDescription></DialogHeader>
 <div className="cu-step-track" aria-hidden="true">{steps.map((s,i)=><span className={i<=step?'complete':''} key={s}/>)}</div>
 {step>0&&<div className="cu-location"><Building2 size={22}/><div><strong>{club?.name}</strong>{step>1&&<p>{date(signedOn)}</p>}</div></div>}
 {saved?<section className="cu-receipt"><Check size={28}/><h3 ref={heading} tabIndex={-1}>CÜ für {club?.name} gespeichert</h3><p>{date(signedOn)}: <strong>{total} Mitgliedschaften</strong>, davon {onlineCount} online. Erfasst von {firstName.trim()} {lastName.trim()}.</p><p>Die Zielerreichung für diesen Standort wurde aktualisiert.</p><button className="button primary" onClick={onClose}>Zur Übersicht</button></section>:<>
 <h3 className="cu-question" ref={heading} tabIndex={-1}>{['Für welchen Standort erfasst du die CÜ?','Für welchen Tag soll die CÜ erfasst werden?','Wie viele Mitgliedschaften wurden abgeschlossen?','Wie viele Online-Mitgliedschaften gab es an diesem Tag?','Ist die Gesamtanzahl korrekt?','Wer hat die CÜ erfasst?'][step]}</h3>
 <form onSubmit={step===5?save:next} className="cu-entry-form">
 {step===0&&<><label>Standort<Select value={clubId} onValueChange={setClubId}><SelectTrigger aria-label="Standort für CÜ" className="picker"><SelectValue placeholder="Standort auswählen"/></SelectTrigger><SelectContent>{snapshot.config.clubs.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></label>{club&&<div className="cu-location"><Building2 size={22}/><strong>{club.name}</strong></div>}<p className="section-note">Bitte den Standort ausdrücklich bestätigen. Alle Zahlen werden nur diesem Club zugeordnet.</p></>}
 {step===1&&<><label>Tag der CÜ<input type="date" value={signedOn} onChange={e=>setSignedOn(e.target.value)} required max={todayBerlin()}/></label><p className="section-note">Erfassung im Berichtsmonat {snapshot.config.period}, nach dem Ausgangsstand vom {date(snapshot.config.asOf)}.</p>{historyError&&<p className="form-error">{historyError}</p>}{entries.some(e=>e.signedOn===signedOn&&!e.cancelledAt)&&<div className="cu-cancel"><p>Für {club?.name} gibt es am {date(signedOn)} bereits eine CÜ.</p>{snapshot.canEdit&&<button type="button" className="text-button danger-text" onClick={()=>setCancelId(entries.find(e=>e.signedOn===signedOn&&!e.cancelledAt)!.id)}>Fehlerhafte CÜ stornieren</button>}</div>}</>}
 {step===2&&<><p className="section-note">Alle Abschlüsse einschließlich Online nach Tarif eintragen. Leere Felder zählen als 0.</p><div className="cu-tariffs">{tariffKeys.map(key=><label key={key}>{tariffLabels[key]}<input aria-label={tariffLabels[key]} type="number" min="0" max="9999" step="1" inputMode="numeric" placeholder="0" value={counts[key]} onChange={e=>setCounts({...counts,[key]:e.target.value})}/></label>)}</div><p className="cu-subtotal">Gesamt: <strong>{Number.isFinite(total)?total:'–'}</strong></p></>}
 {step===3&&<><label>Davon online<input aria-label="Online-Mitgliedschaften" type="number" min="0" max={total} step="1" inputMode="numeric" placeholder="0" value={online} onChange={e=>setOnline(e.target.value)}/></label><p className="section-note">Bereits in den {total} Mitgliedschaften enthalten. Wird nicht noch einmal addiert.</p></>}
 {step===4&&<><div className="cu-total-confirm"><p>{signedOn===todayBerlin()?'Heute':`Am ${date(signedOn)}`} wurden insgesamt</p><strong>{total}</strong><p>Mitgliedschaften abgeschlossen.<br/>Davon {onlineCount} online.</p></div><div className="save-actions"><button type="button" className="button primary" onClick={()=>go(5)}><Check size={17}/>Ja, das ist korrekt</button><button type="button" className="button secondary" onClick={()=>go(2)}>Nein, Zahlen korrigieren</button></div></>}
 {step===5&&<><div className="form-two"><label>Vorname<input value={firstName} onChange={e=>setFirstName(e.target.value)} autoComplete="given-name" required maxLength={80}/></label><label>Nachname<input value={lastName} onChange={e=>setLastName(e.target.value)} autoComplete="family-name" required maxLength={80}/></label></div><p className="section-note">Bestätigt: {total} Mitgliedschaften für {club?.name} am {date(signedOn)}, davon {onlineCount} online.</p></>}
 {error&&<p className="form-error" role="alert">{error}</p>}
 {step!==4&&<button className="button primary full" type="submit" disabled={busy||(step===0&&!club)}>{busy?<RefreshCw size={17} className="spin"/>:step===5?<Save size={17}/>:null}{step===0?`${club?.name||'Standort'} bestätigen`:step===5?'CÜ speichern':'Weiter'}</button>}
 {step>0&&<button type="button" className="text-button" disabled={busy} onClick={()=>go(step===5?4:step-1)}><ChevronLeft size={16}/>Zurück</button>}
 </form>
 {cancelId&&<div className="cu-cancel"><p>Die bisherige CÜ für {club?.name} am {date(signedOn)} stornieren? Ihre Mitgliedschaften werden aus der Zielerreichung entfernt. Danach kann der Tag neu erfasst werden.</p><div className="save-actions"><button className="button danger" disabled={busy} onClick={()=>void cancel()}>Stornierung bestätigen</button><button className="button secondary" disabled={busy} onClick={()=>setCancelId('')}>Abbrechen</button></div></div>}
 </>}
 </DialogContent></Dialog>
}
